import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './modules/Header'
import ScrollToTopButton from './modules/ToUp/ToUp'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Depot',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./icon.png" />
        <meta name="author" content="Ahmed Mansour" />
      </head>
      <body className={inter.className}>
        <Header />
        <hr />
        {children}
        <hr />
        <ScrollToTopButton />
      </body>
    </html>
  )
}
